service: bliblou-roles-config

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-cf-vars

provider:
  name: aws
  runtime: nodejs10.x
  stage: test
  region: eu-west-1

custom:
  product: bliblou
  stage: ${opt:stage, self:provider.stage}
  identityPoolId: !ImportValue ${self:custom.product}-${self:custom.stage}-IdentityPoolId
  userPoolProviderName: !ImportValue ${self:custom.product}-${self:custom.stage}-UserPoolProviderName
  userPoolClient: !ImportValue ${self:custom.product}-${self:custom.stage}-UserPoolClient
  recipesApiGateway: !ImportValue ${self:custom.product}-${self:custom.stage}-RecipesApiGateway
  recipePicturesBucketArn: !ImportValue ${self:custom.product}-${self:custom.stage}-RecipePicturesBucketArn

functions:
  mapRole:
    handler: handler.mapRole

resources:
  - ${file(resources/cognito-roles-mapping.yml)}

